name: one
description: "App Factory - App One"
publish_to: 'none'
version: 1.0.0+1
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # 共享包
  core:
  api_client:
  shared_models:
  ui_kit:
  auth_ui:

  # 状态管理
  flutter_riverpod: ^3.2.0
  riverpod_annotation: ^4.0.1

  # 路由
  go_router: ^17.0.1

  # 存储
  shared_preferences: ^2.2.0

  # UI
  cupertino_icons: ^1.0.8

  # 日志
  logger: ^2.2.0

dev_dependencies:
  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.2
  build_runner: ^2.10.5

flutter:
  uses-material-design: true
